WebNutricion/WebNutricion/Models/AspNetUser.cs
namespace WebNutricion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class AspNetUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUser()
        {
            planAlimentacions = new HashSet<planAlimentacion>();
            planificacionNutricionals = new HashSet<planificacionNutricional>();
            valoresNutricionales = new HashSet<valoresNutricionale>();
        }

        public string Id { get; set; }

        [StringLength(256)]
        public string Email { get; set; }

        public bool EmailConfirmed { get; set; }

        public string PasswordHash { get; set; }

        public string SecurityStamp { get; set; }

        public string PhoneNumber { get; set; }

        public bool PhoneNumberConfirmed { get; set; }

        public bool TwoFactorEnabled { get; set; }

        public DateTime? LockoutEndDateUtc { get; set; }

        public bool LockoutEnabled { get; set; }

        public int AccessFailedCount { get; set; }

        [Required]
        [StringLength(256)]
        public string UserName { get; set; }

        public string Nombre { get; set; }

        public string Apellidos { get; set; }

        public string Telefono { get; set; }

        public string Cedula { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<planAlimentacion> planAlimentacions { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<planificacionNutricional> planificacionNutricionals { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<valoresNutricionale> valoresNutricionales { get; set; }
    }
}

WebNutricion/WebNutricion/Controllers/AspNetUserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebNutricion.Models;

namespace WebNutricion.Controllers
{
    [Authorize(Roles = "Administrador")]

    public class AspNetUserController : Controller
    {
        private NutricionModel db = new NutricionModel();


        // GET: AspNetUser
        public ActionResult Index()
        {
            return View(db.AspNetUsers.ToList());
        }
        public ActionResult ShowAntropometricData(string id)
        {
            // Verifica si el ID no es nulo
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Busca el usuario asociado al ID en la tabla AspNetUsers
            AspNetUser usuario = db.AspNetUsers.FirstOrDefault(u => u.Id == id);

            // Verifica si se encontró el usuario
            if (usuario == null)
            {
                return HttpNotFound("No se encontró ningún usuario asociado a este Id.");
            }

            // Busca los datos nutricionales asociados al ID del usuario
            var valorNutricionalData = db.valoresNutricionales.Where(d => d.idUser == id).OrderByDescending(d => d.fecha).FirstOrDefault();
            var planificacionNutricionalData = db.planificacionNutricionals.Where(d => d.idUser == id).OrderByDescending(d => d.fecha).FirstOrDefault();
            var planAlimentacionData = db.planAlimentacions.Where(d => d.idUser == id).OrderByDescending(d => d.fecha).FirstOrDefault();

            // Crea un modelo de vista que contenga los datos más recientes
            var viewModel = new Tuple<valoresNutricionale, planificacionNutricional, planAlimentacion>(valorNutricionalData, planificacionNutricionalData, planAlimentacionData);

            // Pasa los datos a la vista
            return View(viewModel);
        }


        public ActionResult Progress(string id)
        {
            // Verifica si el ID no es nulo
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Busca el usuario asociado al ID en la tabla AspNetUsers
            AspNetUser usuario = db.AspNetUsers.FirstOrDefault(u => u.Id == id);

            // Verifica si se encontró el usuario
            if (usuario == null)
            {
                return HttpNotFound("No se encontró ningún usuario asociado a este Id.");
            }

            // Busca los datos antropométricos asociados al ID del usuario
            var planificacionNutricionalData = db.planificacionNutricionals.Where(d => d.idUser == id).OrderByDescending(d => d.fecha).ToList();

            // Crea un modelo de vista que contenga las listas de datos antropométricos
            var viewModel = new Tuple<List<planificacionNutricional>>( planificacionNutricionalData);

            // Pasa los datos antropométricos a la vista
            return View(viewModel);
        }

        // GET: ShowAntropometricData/CreateNew
        public ActionResult CreateNew(string motivo, string expectativas, string informacionConsulta, string historial, string Cedula, DateTime fecha, string idUser)
{
    ViewBag.Motivo = motivo;
    ViewBag.Expectativas = expectativas;
    ViewBag.InformacionConsulta = informacionConsulta;
    ViewBag.Historial = historial;
    ViewBag.Cedula = Cedula;
    ViewBag.Fecha = fecha;
    ViewBag.IdUser = idUser;

    return View();
}


        // POST: ShowAntropometricData/CreateNew
        // Este método maneja el envío del formulario para crear un nuevo registro de valoresNutricionale
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNew([Bind(Include = "motivo,expectativas,informacionConsulta,historial,fecha,idUser")] valoresNutricionale valoresNutricionale, string idUser)
        {
            if (ModelState.IsValid)
            {
                // Asignamos el ID de usuario al objeto valoresNutricionale
                valoresNutricionale.idUser = idUser;

                db.valoresNutricionales.Add(valoresNutricionale);
                db.SaveChanges();

                // Redirigimos a la acción Create del controlador Gestion para crear el plan de alimentación
                return RedirectToAction("ShowAntropometricData", new { id = idUser });
            }

            // Si hay un error en el modelo, volvemos a cargar la vista con los errores
            return View(valoresNutricionale);
        }
        // GET: ShowAntropometricData/CreateNew2
        public ActionResult CreateNew2(int peso, int altura, int IMC, int grasacorporal, int metabolismobasal, int caloriasdiarias, int proteinas, int carbohidratos, int grasas, string objetivo, DateTime fecha, string idUser)
        {
            ViewBag.Peso = peso;
            ViewBag.Altura = altura;
            ViewBag.IMC = IMC;
            ViewBag.Grasacorporal = grasacorporal;
            ViewBag.Metabolismobasal = metabolismobasal;
            ViewBag.Caloriasdiarias = caloriasdiarias;
            ViewBag.Proteinas = proteinas;
            ViewBag.Carbohidratos = carbohidratos;
            ViewBag.Grasas = grasas;
            ViewBag.Objetivo = objetivo;
            ViewBag.Fecha = fecha;
            ViewBag.IdUser = idUser;

            return View();

        }

        // POST: ShowAntropometricData/CreateNew2
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNew2([Bind(Include = "peso,altura,IMC,grasacorporal,metabolismobasal,caloriasdiarias,proteinas,carbohidratos,grasas,objetivo,Cedula,fecha,idUser")] planificacionNutricional planificacionNutricional, string idUser)
        {
            if (ModelState.IsValid)
            {
                // Asignar el ID de usuario a los objetos
                planificacionNutricional.idUser = idUser;

                // Agregar los objetos a la base de datos y guardar los cambios
                db.planificacionNutricionals.Add(planificacionNutricional);
                db.SaveChanges();

                // Redireccionar a la acción Index del controlador Home
                return RedirectToAction("ShowAntropometricData", new { id = idUser });
            }

            // Si hay errores en el modelo, volver a cargar la vista con los errores
            return View(planificacionNutricional);
        }

        // GET: ShowAntropometricData/CreateNew2
        public ActionResult CreateNew3(string desayuno, string almuerzo, string merienda, string cena, string calorias, DateTime fecha, string idUser)
        {
            ViewBag.Desayuno = desayuno;
            ViewBag.Almuerzo = almuerzo;
            ViewBag.Merienda = merienda;
            ViewBag.Cena = cena;
            ViewBag.Calorias = calorias;
            ViewBag.Fecha = fecha;
            ViewBag.IdUser = idUser;

            return View();

        }

        // POST: ShowAntropometricData/CreateNew2
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNew3([Bind(Include = "idPlan,desayuno,almuerzo,merienda,cena,calorias,Cedula,fecha,idUser")] planAlimentacion planAlimentacion, string idUser)
        {
            if (ModelState.IsValid)
            {
                // Asignar el ID de usuario a los objetos
                planAlimentacion.idUser = idUser;

                // Agregar los objetos a la base de datos y guardar los cambios
                db.planAlimentacions.Add(planAlimentacion);
                db.SaveChanges();

                // Redireccionar a la acción Index del controlador Home
                return RedirectToAction("ShowAntropometricData", new { id = idUser });
            }

            // Si hay errores en el modelo, volver a cargar la vista con los errores
            return View(planAlimentacion);
        }



        // GET: AspNetUser/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // GET: AspNetUser/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AspNetUser/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,Nombre,Apellidos,Telefono,Cedula")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.AspNetUsers.Add(aspNetUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aspNetUser);
        }

        // GET: AspNetUser/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // POST: AspNetUser/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 

WebNutricion/WebNutricion/Views/AspNetUser/CreateNew.cshtml
@model WebNutricion.Models.valoresNutricionale

@{
    ViewBag.Title = "CreateNew";
}
<body>
    <div class="container">
        <div style="margin-top: 100px;"></div>
        <header>
            <h1>Editar Valores Nutricionales</h1>
        </header>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
                <div class="form-horizontal" style="width: 50%; margin: auto;">
                    <h4>Valores Nutricionales</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <texto>Motivo</texto>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.motivo, new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.Motivo } })
                            @Html.ValidationMessageFor(model => model.motivo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <br />

                    <div class="form-group">
                        <texto>Expectativas</texto>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.expectativas, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.expectativas, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <br />

                    <div class="form-group">
                        <texto>Informacion de consulta</texto>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.informacionConsulta, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.informacionConsulta, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <br />

                    <div class="form-group">
                        <texto>Historial</texto>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.historial, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.historial, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <br />

                    <div class="form-group">
                        <texto>Fecha</texto>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control", @Value = DateTime.Now.ToShortDateString() } })
                            @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <br />
                    <div class="text mb-1" style="font-size: 14px; color: #26798e; display: none;">
                        @Html.LabelFor(model => model.idUser, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.idUser, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.idUser, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Guardar" class="btn btn-lg btn-primary btn-block" style="background-color: #26798e; border-color: #26798e;" />
                        </div>
                    </div>
                </div>

                }
            </div>
</body>


    <style>
        body {
            background-image: url('../../webstylemain/assets/img/logos/nutricion-activa.jpg');
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
        }

        h1 {
            font-size: 3em;
            font-weight: 300;
            line-height: 1em;
            text-align: center;
            color: #26798E;
            margin-bottom: 40px;
        }

        .container th h1 {
            font-weight: bold;
            font-size: 1em;
            text-align: left;
            color: #26798E;
        }

        /*    .container td {
            font-weight: normal;
            font-size: 1em;
            -webkit-box-shadow: 0 2px 2px -2px #0E1119;
            -moz-box-shadow: 0 2px 2px -2px #0E1119;
            box-shadow: 0 2px 2px -2px #0E1119;
        }*/



        .container td, .container th {
            padding-bottom: 2%;
            padding-top: 2%;
            padding-left: 2%;
        }

        /* Background-color of the odd rows */
        .container tr:nth-child(odd) {
            background-color: #26798E;
        }

        /* Background-color of the even rows */
        .container tr:nth-child(even) {
            background-color: #26798E;
        }

        .container th {
            background-color: #63caa7;
        }

        .container td:first-child {
            color: black;
        }

        .container tr:hover {
            background-color: #63caa7;
            -webkit-box-shadow: 0 6px 6px -6px #0E1119;
            -moz-box-shadow: 0 6px 6px -6px #0E1119;
            box-shadow: 0 6px 6px -6px #0E1119;
        }

        .container td:hover {
            background-color: #FFC172;
            color: #403E10;
            font-weight: bold;
            box-shadow: #7F7C21 -1px 1px, #7F7C21 -2px 2px, #7F7C21 -3px 3px, #7F7C21 -4px 4px, #7F7C21 -5px 5px, #7F7C21 -6px 6px;
            transform: translate3d(6px, -6px, 0);
            transition-delay: 0s;
            transition-duration: 0.4s;
            transition-property: all;
            transition-timing-function: line;
        }
    </style>

WebNutricion/WebNutricion/Views/AspNetUser/Index.cshtml
@model IEnumerable<WebNutricion.Models.AspNetUser>

@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html lang="en">

<body>

    <div style="margin-top: 150px;"></div>
    <header>
        <div>
            <h1>Clientes</h1>
        </div>
    </header>

<table class="container">
    <thead>
        <tr>
            <th><h1>Email</h1></th>
            <th><h1>Usuario</h1></th>
            <th><h1>Nombre</h1></th>
            <th><h1>Apellidos</h1></th>
            <th><h1>Telefono</h1></th>
            <th><h1>Cedula</h1></th>
            <th><h1>Acciones</h1></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Email)</td>
                <td>@Html.DisplayFor(modelItem => item.UserName)</td>
                <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                <td>@Html.DisplayFor(modelItem => item.Apellidos)</td>
                <td>@Html.DisplayFor(modelItem => item.Telefono)</td>
                <td>@Html.DisplayFor(modelItem => item.Cedula)</td>
                <td>
                    <hr />
                    @using (Html.BeginForm("ShowAntropometricData", "AspNetUser", FormMethod.Get))
                    {
                        <div class="form-group">
                            <input type="hidden" value="@item.Id" name="id" class="form-control" />
                        </div>
                        <button type="submit" class="btn btn-primary">Gestionar Cliente</button>
                    }
                    @using (Html.BeginForm("Progress", "AspNetUser", FormMethod.Get))
                    {
                        <div class="form-group">
                            <input type="hidden" value="@item.Id" name="id" class="form-control" />
                        </div>
                        <button type="submit" class="btn btn-primary">Progreso</button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

</body>
</html>


<style>
    body {
        background-image: url(/WebStyleMain/assets/img/pexels-alex-green-5699486.jpg);
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center;
    }

    h1 {
        font-size: 3em;
        font-weight: 300;
        line-height: 1em;
        text-align: center;
        color: #26798E;
        margin-bottom: 40px;
    }

    .container th h1 {
        font-weight: bold;
        font-size: 1em;
        text-align: left;
        color: #26798E;
    }

    /*    .container td {
        font-weight: normal;
        font-size: 1em;
        -webkit-box-shadow: 0 2px 2px -2px #0E1119;
        -moz-box-shadow: 0 2px 2px -2px #0E1119;
        box-shadow: 0 2px 2px -2px #0E1119;
    }*/



    .container td, .container th {
        padding-bottom: 2%;
        padding-top: 2%;
        padding-left: 2%;
    }

    /* Background-color of the odd rows */
    .container tr:nth-child(odd) {
        background-color: #26798E;
    }

    /* Background-color of the even rows */
    .container tr:nth-child(even) {
        background-color: #26798E;
    }

    .container th {
        background-color: #63caa7;
    }

    .container td:first-child {
        color: black;
    }

    .container tr:hover {
        background-color: #63caa7;
        -webkit-box-shadow: 0 6px 6px -6px #0E1119;
        -moz-box-shadow: 0 6px 6px -6px #0E1119;
        box-shadow: 0 6px 6px -6px #0E1119;
    }

    .container td:hover {
        background-color: #FFC172;
        color: #403E10;
        font-weight: bold;
        box-shadow: #7F7C21 -1px 1px, #7F7C21 -2px 2px, #7F7C21 -3px 3px, #7F7C21 -4px 4px, #7F7C21 -5px 5px, #7F7C21 -6px 6px;
        transform: translate3d(6px, -6px, 0);
        transition-delay: 0s;
        transition-duration: 0.4s;
        transition-property: all;
        transition-timing-function: line;
    }
</style>

WebNutricion/WebNutricion/Views/AspNetUser/Progress.cshtml
@using Newtonsoft.Json


@model Tuple<List<WebNutricion.Models.planificacionNutricional>>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="~/WebStyleAspUser/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <link href="~/WebStyleAspUser/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<style>
    /* Estilos personalizados */
    .heading-section {
        color: #26798e; /* Color azul */
        text-align: center;
    }

        .heading-section h2 {
            margin-top: 5px; /* Margen superior */
        }

        .heading-section h3 {
            margin-top: 5px; /* Margen superior */
        }

    .border-left-plan {
        border-left: 0.25rem solid #26798e !important;
    }

    body {
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center;
    }
</style>

<div style="margin-top: 150px;"></div>
<div class=" text-center mb-5">
    <h3 class="heading-section mt-5 ">Progreso</h3>
</div>
<div>
    <div class="container">
        <div class="row justify-content-center align-items-start">
            @if (Model.Item1.Any())
            {
                foreach (var item in Model.Item1)
                {

                    <div class="col-xl-6 col-md-6 mb-4">
                        <div class="card border-left-plan shadow h-100 py-2">
                            <div class="card-body">
                                <h4 class=" style="color: #26798e;">Planificacion Nutricional:</h4>
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text mb-1" style="font-size: 14px; color: #26798e;">
                                            Peso : @item.peso kg

                                        </div>
                                        <div class="text mb-1" style="font-size: 14px; color: #26798e;">
                                            Altura: @item.altura cm
                                        </div>
                                        <div class="text mb-1" style="font-size: 14px; color: #26798e;">
                                            IMC: @item.IMC %
                                        </div>
                                        <div class="text mb-1" style="font-size: 14px; color: #26798e;">
                                            Grasa Corporal: @item.grasacorporal %
                                        </div>
                                        <div class="text mb-1" style="font-size: 14px; color: #26798e;">
                                            Metabolismo Basal: @item.metabolismobasal
                                        </div>
                                        <div class="text mb-1" style="font-size: 14px; color: #26798e;">
                                            Calorias Diarias: @item.caloriasdiarias kcal
                                        </div>
                                        <div class="text mb-1" style="font-size: 14px; color: #26798e;">
                                            Proteinas: @item.proteinas %
                                        </div>
                                        <div class="text mb-1" style="font-size: 14px; color: #26798e;">
                                            Carbohidratos: @item.carbohidratos %
                                        </div>
                                        <div class="text mb-1" style="font-size: 14px; color: #26798e;">
                                            Grasas: @item.grasas %
                                        </div>
                                        <div class="text mb-1" style="font-size: 14px; color: #26798e;">
                                            Objetivo: @item.objetivo
                                        </div>
                                        <div class="text mb-1" style="font-size: 14px; color: #26798e;">
                                            Fecha: @item.fecha
                                        </div>
                                        <div class="text mb-1" style="font-size: 14px; color: #26798e; display: none;">
                                            IdUser: @item.idUser
                                        </div>

                                    </div>
                                </div>
                                <div>
                                </div>
                            </div>
                        </div>
                    </div>

                }
            }
            else
            {
                <p>No se ha encontrado registro del progreso asociados a esta usuario.</p>
            }


        </div>

        <div class="col-md-6">
            <a href="@Url.Action("index", "AspNetUser")" class="btn btn-lg btn-primary btn-block" style="background-color: #26798e; border-color: #26798e;">Regresar</a>
        </div>
    </div>
</div>
    </div>

<script src="~/WebStyleAspUser/vendor//jquery/jquery.min.js"></script>
<script src="~/WebStyleAspUser/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/WebStyleAspUser/vendor/jquery-easing/jquery.easing.min.js"></script>
<script src="~/WebStyleAspUser/js/sb-admin-2.min.js"></script>
<script src="~/WebStyleAspUser/vendor/chart.js/Chart.min.js"></script>
<script src="~/WebStyleAspUser/js/demo/chart-area-demo.js"></script>
<script src="~/WebStyleAspUser/js/demo/chart-pie-demo.js"></script>